// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rwmfoqgrvinrcxkjtzdz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bWZvcWdydmlucmN4a2p0emR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNzM3NzcsImV4cCI6MjA0ODk0OTc3N30.-3jeYYz_tqAq5QtlBog6rcD5pMOP7095qu31Wqls8Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);